id: Vendr.PaymentProviders.Square
name: Square
logo: square.svg
type: PaymentProvider
supportedBy: community

packageVersion: 1.0.2
docVersions:
  next: 2.0.0
  current: 1.0.0
  previous: 

links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/